version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api.seq-validator.dev
    env_file: .env
    networks:
      - seqnet
    ports:
      - "9001:9001"
  mongo:
    image: mongo:5.0.14
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_DATA_DIR=/data/dir
    volumes:
      - mongodb_data:/data/db
    networks:
      - seqnet
    ports:
      - "27017:27017"
  mongo-admin:
    image: mongo-express:latest
    container_name: mongodb_adm
    restart: always
    depends_on:
      - mongo
    networks:
      - seqnet
    ports:
      - "9002:8081"
volumes:
  mongodb_data:
    driver: local
networks:
  seqnet:
    driver: bridge

